name: fire_drive
description: A new Flutter project with firbase auth and storage.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.0
  firebase_storage: ^10.1.0

  file_picker: ^4.5.1
  lottie: ^1.2.2
  sizer: ^2.0.14
  flutter_slidable: ^1.2.0
  flutter_downloader: ^1.7.3
  permission_handler: ^9.2.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  get_it: ^7.0.0
  path_provider: ^2.0.5

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/firedrive.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/